# Generated by Django 4.2.7 on 2023-11-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioativo',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
