# Generated by Django 4.2.7 on 2023-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_assets_userassets_users_remove_userasset_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='123123', max_length=255),
            preserve_default=False,
        ),
    ]
