# Generated by Django 4.2.7 on 2023-11-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_usuarioativo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarioativo',
            name='low_tunnel',
        ),
        migrations.RemoveField(
            model_name='usuarioativo',
            name='top_tunnel',
        ),
    ]
