# Generated by Django 4.2.7 on 2023-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassets',
            name='refresh_time',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
