# Generated by Django 4.2.7 on 2023-11-03 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_delete_usuarioativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_tunnel', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('top_tunnel', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.ativo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracoes.usuario')),
            ],
        ),
    ]
