# Generated by Django 4.2.7 on 2023-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_alter_assets_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
