# Generated by Django 4.2.7 on 2023-11-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0010_alter_assetprices_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetprices',
            old_name='asset',
            new_name='asset_id',
        ),
    ]
