# Generated by Django 4.2.7 on 2023-11-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0011_rename_asset_assetprices_asset_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetprices',
            old_name='asset_id',
            new_name='asset',
        ),
    ]
